ninjas
coderdojobraga/bokken-attempt-1 pull request #5
Opened 2017-08-26 09:37 UTC by ZePedroResende

2017-08-26 11:14 UTC, frm requested changes
This is not quite there. You can see my comments below, but we also should discuss PR title and descriptions.

You expect me to review your code yet you give me no context as to what is happening. The PR title simply says "ninjas".

From reading the code I ASSUME it's about adding the ninja resource. But this is now that the application is in the beginning and it is easy to INFER what is happening. You should always use a descriptive title and if possible a complementing description (although not mandatory if the PR title is self-explanatory. A good example would be if you found a bug and had to explain how and why it happens and how you fixed it).

Finally, you are missing specs and apparently, you added the resource but I see no migration anywhere. Your validations are also a bit weak in the sense that you check for presence but that's it.

2017-08-26 11:14 UTC, frm commented on app/assets/stylesheets/ninjas.scss
> +// Place all the styles related to the ninjas controller here.
File not needed, delete please.

2017-08-26 11:14 UTC, frm commented on app/assets/stylesheets/scaffolds.scss
> +  background-color: #fff;
Where is this coming from?

2017-08-26 11:14 UTC, frm commented on app/controllers/ninjas_controller.rb
> +  # GET /ninjas.json
Please remove these comments, the methods are self-explanatory if we are following rest.

2017-08-26 11:14 UTC, frm commented on app/controllers/ninjas_controller.rb
> +  before_action :set_ninja, only: [:show, :edit, :update, :destroy]
Setting resources on callbacks is a bad practice.

Sure, it eliminates duplication, but it also means that you will lose context. If am reading a method that suddenly calls `@ninja`, where is that coming from? And actions like `show` are empty. Naturally, I'll be thinking "ok, this does nothing", yet a variable is used in the view.

I'd rather if you set the variable explicitly in each action.

2017-08-26 11:14 UTC, frm commented on app/controllers/ninjas_controller.rb
> +        format.json { render :show, status: :created, location: @ninja }
We're not doing `json`, you can just have the `html` part and leave out the `respond_to` block

2017-08-26 11:14 UTC, frm commented on app/controllers/ninjas_controller.rb
> +        format.html { redirect_to @ninja, notice: "Ninja was successfully updated." }
Same as before

2017-08-26 11:14 UTC, frm commented on app/controllers/ninjas_controller.rb
> +      format.html { redirect_to ninjas_url, notice: "Ninja was successfully destroyed." }
Same as before

2017-08-26 11:14 UTC, fribmendes commented on app/assets/stylesheets/table.css
> +table {
Where's this coming from?

2017-08-26 11:14 UTC, fribmendes commented on app/controllers/ninjas_controller.rb
> +  def checkin_ninja
First, this is out of the scope of this PR. If you are adding a `Ninja` resource, let's do that first and think about check ins later.

Second, it's a typo, it's `check_in`, not `checkin`.

Third, this is not REST. We don't create methods other than the default REST ones. To add something like this, you would create a `CheckInController` that would receive a parameter for the `user_id` and add a `check_in`

2017-08-26 11:14 UTC, fribmendes commented on app/models/ninja.rb
> +  validates :n_ninja, :n_mentor, :nome, :nome_ed, :contacto_ed, presence: true
These attribute names shouldn't be this way.

First, I don't know what they are. What is `n_ninja` and `n_mentor`? If I am reading your code, I should be able to understand what is happening and, for the life of me, there's no way I can guess what `n_ninja` is.

Second, we are writing code in English, let's not soil the database with portuguese-named attributes.

2017-08-26 11:14 UTC, fribmendes commented on app/views/layouts/application.html.slim
> +   title Bokken
Is this indentation right?

2017-08-26 11:14 UTC, fribmendes commented on app/views/ninjas/index.html.slim
> += stylesheet_link_tag "table"
Why are we adding stylesheets here?

2017-08-26 11:14 UTC, fribmendes commented on app/views/ninjas/edit.html.slim
> +| \
Why this?

2017-08-26 11:14 UTC, fribmendes commented on app/views/ninjas/new.html.slim
> +
Extra newline

2017-08-26 11:14 UTC, fribmendes commented on app/views/ninjas/show.html.slim
> +
Extra newline

2017-08-26 11:14 UTC, fribmendes commented on app/views/ninjas/show.html.slim
> +  strong Nome encarregado de educacao:
Please use proper accentuation.

2017-08-26 11:14 UTC, fribmendes commented on config/initializers/assets.rb
> +Rails.application.config.assets.precompile += %w( admin.js admin.css table.css )
You don't need this. Just require the files in the `application.{js,css,scss}` manifests.

2017-08-26 11:14 UTC, fribmendes commented on config/routes.rb
> +		put :checkin_mentor
These are terrible routes for reasons mentioned before.

2017-08-26 11:17 UTC, fribmendes commented
Also, please start doing the PRs from our own repo instead of your fork. You are trying to merge from `ZePedroResende:dev` to `coderdojobraga:master`. To allow us to do further testing you it should be `coderdojobraga:zpr-ninjas` to `coderdojobraga:master`.

Please use the convention `<initials>-<feature>` when naming your branch so we know who's working on what, when using the command line and not GitHub.

2017-08-26 12:04 UTC, ZePedroResende commented
Gonna be more carefull with the PR title and description .
You clarified some doubts i had with the handle of the check in , but has you said theres no need to add it in this PR i'll rewrite it later . 
The rest ,now that you point them , are obvious mistakes and i should have known better .
I'll rewrite and correct whats needed and try to submit later today an improve version this time with specs .
Thanks for reviewing my awful code, writing this and sorry for wasting your time

2017-08-26 19:57 UTC, fribmendes commented
Mate, you don't need to apologize. Nobody is born with knowledge, you learn by doing and that is fine.

Code reviews are to help you improve your code, not to batter you. It's not a time waste, you're the one implementing it so we should be happy that you do it and help you get it right.

2017-08-29 09:41 UTC, fribmendes commented
Closing in favor of #7

2017-08-29 09:41 UTC, closed without merging