Add ninja resource
coderdojobraga/bokken-attempt-1 pull request #7
Opened 2017-08-29 02:12 UTC by ZePedroResende

Create, edit and list ninjas with basic information (name , guardian information and miscellaneous comment)

2017-08-29 09:39 UTC, frm requested changes

2017-08-29 09:39 UTC, fribmendes commented on app/controllers/ninjas_controller.rb
> +    respond_to do |format|
You don't need the `respond_to` block, just the content.

2017-08-29 09:39 UTC, fribmendes commented on app/controllers/ninjas_controller.rb
> +    respond_to do |format|
Same as before

2017-08-29 09:39 UTC, fribmendes commented on app/controllers/ninjas_controller.rb
> +    respond_to do |format|
Same as before

2017-08-29 09:39 UTC, fribmendes commented on app/models/ninja.rb
> +  validates_format_of :guardian_contact, with:  /@/
Why do we need this? Are you trying to validate an email?

2017-08-29 09:39 UTC, fribmendes commented on app/views/ninjas/index.html.slim
> +br/
Unnecessary

2017-08-29 09:39 UTC, fribmendes commented on spec/controllers/ninja_controller_spec.rb
> +    before { @ninjas = FactoryGirl.create_list(:ninja, 5) }
You don't need the before blocks.

2017-08-29 09:40 UTC, frm requested changes

2017-08-29 09:40 UTC, fribmendes commented on Gemfile
> +  gem "rails-controller-testing"
Why do you need this gem?

2017-08-29 23:02 UTC, ZePedroResende commented on app/models/ninja.rb
> +  validates_format_of :guardian_contact, with:  /@/
The length validation i saw on atomic and though it was a best practice, should have asked in retrospective. 
I assumed that they give email as a contact and a way to get remainders of sessions. Didn't use a regex because it seemed a little overkill. 
Would it be best to have a phone number and email fields instead of a single contact field ?

2017-08-29 23:09 UTC, ZePedroResende commented on app/views/ninjas/index.html.slim
> +br/
The order by name  or the table ?

2017-09-03 14:58 UTC, fribmendes commented on app/views/ninjas/index.html.slim
> +br/
The `/` but the views are temporary, let's ignore them for now

2017-09-14 17:47 UTC, frm approved these changes

2017-09-14 22:56 UTC, merged